### ISSUE TITLE
help on using mutation observer in the execute script function

### ISSUE THREAD

**Issue by masihfathi** [fjaguero/twitter-replies-counter#1]
is it possible to help me on this question , "https://stackoverflow.com/questions/45119707/chrome-extension-execute-script-wait-for-ajax-response-complete"

**Comment by fjaguero** [comment]
I didn't cleary understand what are you doing. Did you try to use jQuery's AJAX wrapper? If your problem is that callback between background and the client script, I would recommend you to send the message from the client to backgound, like:

```javascript
chrome.extension.sendMessage({'count': total})
```

That way you can send a message to the background script whenever you want (in this case, when the request is completed). 

Then in background you just handle that one:

```javascript
// Listen to content.js events
chrome.extension.onMessage.addListener(
  function(request, sender, sendResponse) {
    if (request.output) {
      sendData(output)
    }
  }
);
````

This is exactly what I'm doing in this extension.

**Comment by masihfathi** [comment]
i create an extension which this extension reload page after seconds which got from popup.html from user, when a reload occur in the page for example github.com, the script in the scriptinjection.js file click on the buttons, all things get done but in a specific page for example in github.com/... , github have a button which load content via ajax, the script click on the button but dose not wait to get result which load with ajax after for example 3 seconds.

**Comment by fjaguero** [comment]
If you can pass me an example of a webpage, I can have a look on how to use the mutation observers

**Comment by masihfathi** [comment]
can i have your personal contact to talk more about this issue?

**Comment by fjaguero** [comment]
I prefer to discuss it here so it's helpful for everyone. 

I build another example that uses the mutation observer on the inject.js. You can download it from [here](https://cl.ly/lcTs/download/medium-observers-test-extension.zip). It just tracks the `h3` from medium.com. Whenever a new h3 is displayed, the values are catched. You will need to do the same but target the contents inside that AJAX you are mentioning. Instead of doing a console.log, you can use [sendMessage](https://developer.chrome.com/extensions/messaging) and pass those values to the background.

![image](https://d26dzxoao6i3hh.cloudfront.net/items/1M292n2P0k2y0Y1l1S1E/Screen%20Recording%202017-07-19%20at%2010.13%20a.%20m..gif)

**Comment by masihfathi** [comment]
thanks for your great help, the problem solved by using content script instead of executeScript file, i used executeScript to execute script file after reload occur on page and i used mutation observer in the execute script file but the problem arises cause after executing script file the function callback call and javascript get away from mutation observer, as your help i used content script and mutation observer work as expected.

**Comment by fjaguero** [comment]
Great to hear that!
